### ISSUE TITLE
Got several EPEERINVALID warnings.

### ISSUE THREAD

**Issue by gearsdigital** [adonisjs/adonis-validation-provider#1]
I migrated today to adonis-framework 2 and got some EPEERINVALID warnings.

```
npm WARN EPEERINVALID adonis-ace@2.0.4 requires a peer of adonis-fold@^2.0.0 but none was installed.
npm WARN EPEERINVALID adonis-framework@2.0.4 requires a peer of adonis-fold@^2.0.0 but none was installed.
npm WARN EPEERINVALID adonis-lucid@2.0.1 requires a peer of adonis-fold@^2.0.0 but none was installed.
npm WARN EPEERINVALID adonis-commands@2.0.1 requires a peer of adonis-fold@^2.0.0 but none was installed.
```

**Comment by thetutlage** [comment]
Yes you will have to install the latest version of `adonis-fold`, or there is a better way to do it. Create a new 2.0 application and replace your `app` folder with it

**Comment by gearsdigital** [comment]
Yeah, i created a new app and copied my files over. If i change my package.json to `"adonis-fold": "^2.*` I got another warning:

`adonis-validation-provider@2.0.0 requires a peer of adonis-fold@^1.0.0 but none was installed.`

#### strip from package.json

```
    "adonis-ace": "^2.0.4",
    "adonis-commands": "^2.0.1",
    "adonis-fold": "^2.*",
    "adonis-framework": "^2.0.4",
    "adonis-lucid": "^2.0.1",
    "adonis-validation-provider": "^2.0.0",
```

**Comment by gearsdigital** [comment]
Thats maybe the reason i got warnings while using (submitting a form) my app?

```
Warning: a promise was rejected with a non-error: [object String]
Warning: a promise was rejected with a non-error: [object Array] at processImmediate [as _immediateCallback] (timers.js:384:17)
```

**Comment by thetutlage** [comment]
My bad, i forgot to update the validation provider dependencies. Released an update `2.0.1` for validation provider

**Comment by gearsdigital** [comment]
No problem! Thank you. EPEERINVALID warnings are gone now but got still these promise errors. Maybe this is related to `adonis-validation-provider`?

**Comment by thetutlage** [comment]
I would need more info, from where you are getting this, how the code is ?

**Comment by gearsdigital** [comment]
Sure! The warning happens every time I submit the form (post).

#### Terminal

```
Warning: a promise was rejected with a non-error: [object String]
    at /sapin/node_modules/indicative/src/Validator/index.js:71:8
    at _validateField (/sapin/node_modules/indicative/src/Validator/index.js:69:10)
    at /sapin/node_modules/indicative/src/Validator/index.js:116:14
    at processImmediate [as _immediateCallback] (timers.js:384:17)
From previous event:
    at /sapin/node_modules/indicative/src/Validator/index.js:114:14
    at Object.Validator.validate (/sapin/node_modules/indicative/src/Validator/index.js:113:10)
    at /sapin/node_modules/adonis-validation-provider/src/Validator/schema.js:31:10
    at SchemaValidator.validate (/sapin/node_modules/adonis-validation-provider/src/Validator/schema.js:29:12)
    at Object.Validator.validate (/sapin/node_modules/adonis-validation-provider/src/Validator/index.js:36:32)
    at AuthController.login (/sapin/app/Http/Controllers/AuthController.js:28:38)
    at next (native)
    at /sapin/node_modules/adonis-framework/src/Middleware/index.js:140:5
    at next (native)
    at onFulfilled (/sapin/node_modules/co/index.js:65:19)
    at /sapin/node_modules/co/index.js:54:5
    at co (/sapin/node_modules/co/index.js:50:10)
    at toPromise (/sapin/node_modules/co/index.js:118:63)
    at next (/sapin/node_modules/co/index.js:99:29)
    at onFulfilled (/sapin/node_modules/co/index.js:69:7)
    at /sapin/node_modules/co/index.js:54:5
    at co (/sapin/node_modules/co/index.js:50:10)
    at Object.helpers.callRouteAction (/sapin/node_modules/adonis-framework/src/Server/helpers.js:29:3)
    at Server._finalHandler (/sapin/node_modules/adonis-framework/src/Server/index.js:54:13)
    at finalHandler (/sapin/node_modules/adonis-framework/src/Server/index.js:90:12)
    at next (native)
    at onFulfilled (/sapin/node_modules/co/index.js:65:19)
    at /sapin/node_modules/co/index.js:54:5
    at co (/sapin/node_modules/co/index.js:50:10)

Warning: a promise was rejected with a non-error: [object Array]
    at processImmediate [as _immediateCallback] (timers.js:384:17)
From previous event:
    at /sapin/node_modules/indicative/src/Validator/index.js:114:14
    at Object.Validator.validate (/sapin/node_modules/indicative/src/Validator/index.js:113:10)
    at /sapin/node_modules/adonis-validation-provider/src/Validator/schema.js:31:10
    at SchemaValidator.validate (/sapin/node_modules/adonis-validation-provider/src/Validator/schema.js:29:12)
    at Object.Validator.validate (/sapin/node_modules/adonis-validation-provider/src/Validator/index.js:36:32)
    at AuthController.login (/sapin/app/Http/Controllers/AuthController.js:28:38)
    at next (native)
    at /sapin/node_modules/adonis-framework/src/Middleware/index.js:140:5
    at next (native)
    at onFulfilled (/sapin/node_modules/co/index.js:65:19)
    at /sapin/node_modules/co/index.js:54:5
    at co (/sapin/node_modules/co/index.js:50:10)
    at toPromise (/sapin/node_modules/co/index.js:118:63)
    at next (/sapin/node_modules/co/index.js:99:29)
    at onFulfilled (/sapin/node_modules/co/index.js:69:7)
    at /sapin/node_modules/co/index.js:54:5
    at co (/sapin/node_modules/co/index.js:50:10)
    at Object.helpers.callRouteAction (/sapin/node_modules/adonis-framework/src/Server/helpers.js:29:3)
    at Server._finalHandler (/sapin/node_modules/adonis-framework/src/Server/index.js:54:13)
    at finalHandler (/sapin/node_modules/adonis-framework/src/Server/index.js:90:12)
    at next (native)
    at onFulfilled (/sapin/node_modules/co/index.js:65:19)
    at /sapin/node_modules/co/index.js:54:5
    at co (/sapin/node_modules/co/index.js:50:10)
```

#### Related code

```
// app/Http/routes.js
Route.post('/login', 'AuthController.login');

// app/Http/Controllers/AuthController.js
  *login(request, response) {

    let clean = this.sanitize.escape(request.all());

    // validate login form
    let messages = {'email': 'E-Mail-Adresse oder Passwort falsch.'};
    let rules = {email: 'required|email'};
    let validation = yield Validator.validate(rules, clean, messages);

    if (validation.fails()) {
      let view = yield response.view('login.html', {
        error: validation.errors[0].message,
        email: request.input('email')
      });
      response.send(view);
      return;
    }

    // authenticate user
    let hasUser = yield this.userAuthService.authenticate(clean);
    if (hasUser.length) {
      yield request.session.put('authenticated', '1');
      response.redirect('settings');
      return;
    }

    response.redirect('login');

  }
```

**Comment by thetutlage** [comment]
It says you are rejecting a promise without an error. May be an issue with `this.userAuthService.authenticate` are you rejecting with an error from this service ?

**Comment by gearsdigital** [comment]
Nope, I think that is not the problem. Please note the `return` statement near `if (validation.fails())`... The error occurs even if I remove the code near `this.userAuthService.authenticate`.

**Comment by thetutlage** [comment]
Okay, i believe i will have to check it properly, coz tests are passing. Something weird seems to be going on

**Comment by gearsdigital** [comment]
Do you need a demo repo? Maybe I could setup one for you?

**Comment by thetutlage** [comment]
No i am able to figure it out, it is with the `indicative` itself. Also it is a warning not an error. Let me fix it.

**Comment by gearsdigital** [comment]
Okay, sounds cool. Do you need a new issue on `adonis-validation-provider`?

Let me know if you need further informations to reproduce that issue.

**Comment by thetutlage** [comment]
No, i have it. https://github.com/petkaantonov/bluebird/issues/832 . They somehow came with an updated that one needs to throw an error always from a promise. Looking for a stable workaround

Also it happens in `development` mode. http://bluebirdjs.com/docs/api/environment-variables.html

**Comment by gearsdigital** [comment]
Okay. Thank you for your effort.

**Comment by thetutlage** [comment]
Fixed as of latest version. `npm install --save adonis-validation-provider@2.0.2`
