### ISSUE TITLE
 npm: Installation failed

### ISSUE THREAD

**Issue by JZLeung** [adonisjs/adonis-validation-provider#37]
```
✖ npm: Installation failed

=============================================
Installation failed due to following error
=============================================
Command failed: npm install --save @adonisjs/validator
npm ERR! Unexpected end of input at 1:8289
npm ERR! oad/cross-env-5.0.0.tgz"},"engines":{"node":">=4.0"},"_hasShrinkwrap"
npm ERR!                               ^

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lynnleung/.npm/_logs/2018-02-12T10_14_43_231Z-debug.log
```
for more
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@adonisjs/validator' ]
2 info using npm@5.3.0
3 info using node@v8.9.1
4 verbose npm-session cd870496c78d4183
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npm.taobao.org/@adonisjs%2fvalidator 487ms (from cache)
8 silly pacote tag manifest for @adonisjs/validator@latest fetched in 505ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @adonisjs/validator@5.0.3 checking installable status
14 http fetch GET 304 https://registry.npm.taobao.org/@adonisjs%2fgeneric-exceptions 107ms (from cache)
15 silly pacote range manifest for @adonisjs/generic-exceptions@^2.0.0 fetched in 109ms
16 silly resolveWithNewModule @adonisjs/generic-exceptions@2.0.0 checking installable status
17 http fetch GET 304 https://registry.npm.taobao.org/lodash 517ms (from cache)
18 http fetch GET 304 https://registry.npm.taobao.org/indicative 519ms (from cache)
19 silly pacote range manifest for lodash@^4.17.5 fetched in 520ms
20 silly resolveWithNewModule lodash@4.17.5 checking installable status
21 silly pacote range manifest for indicative@^5.0.5 fetched in 522ms
22 silly resolveWithNewModule indicative@5.0.5checking installable status
23 http fetch GET 304 https://registry.npm.taobao.org/upcast 115ms (from cache)
24 silly pacote range manifest for upcast@^2.1.1 fetched in 117ms
25 silly resolveWithNewModule upcast@2.1.2 checking installable status
26 http fetch GET 304 https://registry.npm.taobao.org/node-exceptions 387ms (from cache)
27 silly pacote range manifest for node-exceptions@^3.0.0 fetched in 389ms
28 silly resolveWithNewModule node-exceptions@3.0.0 checking installable status
29 http fetch GET 304 https://registry.npm.taobao.org/cross-env 659ms (from cache)
30 silly fetchPackageMetaData error for cross-env@^5.1.0 Unexpected end of input at 1:8289
30 silly fetchPackageMetaData oad/cross-env-5.0.0.tgz"},"engines":{"node":">=4.0"},"_hasShrinkwrap"
30 silly fetchPackageMetaData     ^
31 verbose stack SyntaxError: Unexpected end of input at 1:8289
31 verbose stack oad/cross-env-5.0.0.tgz"},"engines":{"node":">=4.0"},"_hasShrinkwrap"
31 verbose stack                                       ^
31 verbose stack     at Object.parseJSON (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
31 verbose stack     at parse (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
31 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
31 verbose stack     at <anonymous>
31 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
32 verbose cwd /Users/lynnleung/workspace/adonis-demo
33 verbose Darwin 17.4.0
34 verbose argv "/usr/local/Cellar/node/8.9.1/bin/node" "/usr/local/bin/npm" "install" "--save" "@adonisjs/validator"
35 verbose node v8.9.1
36 verbose npm  v5.3.0
37 error Unexpected end of input at 1:8289
37 error oad/cross-env-5.0.0.tgz"},"engines":{"node":">=4.0"},"_hasShrinkwrap"
37 error                               ^
38 verbose exit [ 1, true ]
```

**Comment by JZLeung** [comment]
maybe the source of taobao to cause this error.
